### ISSUE TITLE
Missing field `float_return_register`.

### ISSUE THREAD

**Issue by Nwqda** [fkie-cad/cwe_checker#265]
Hi @Enkelmann,

Thank you for the fix [#263](https://github.com/fkie-cad/cwe_checker/pull/263), I have git pull the latest changes and re-compile cwe_check, then I tested again with the same binary that I've shared with you yesterday and I got the following error this time:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `float_return_register`", line: 35315861, column: 5)', src/caller/src/main.rs:399:64
stack backtrace:
   0: rust_begin_unwind
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14
   2: core::result::unwrap_failed
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/result.rs:1617:5
   3: cwe_checker::main

```
Do you have any idea?

**Comment by Enkelmann** [comment]
I think you just need to uninstall (`make uninstall`) and then reinstall the cwe_checker again. The error message looks to me as if it is caused by a recent change to the Ghidra plugin contained in the cwe_checker, which probably is not up-to-date in your current installation. To make sure that the plugin is properly updated you need to run `make uninstall` first.

**Comment by Nwqda** [comment]
My bad... it worked.
Again, thanks for all.
