### ISSUE TITLE
Potentially Incorrect Boolean Negation Semantics on Bitvectors

### ISSUE THREAD

**Issue by JamesShaker** [fkie-cad/cwe_checker#268]
Hello!

On line 83 of `src/cwe_checker_lib/src/intermediate_representation/bitvector.rs` within the `un_op` function the `BoolNegate` case is handled by the following code:
```
if self.is_zero() {
    Ok(Bitvector::from_u8(1))
} else {
    Ok(Bitvector::from_u8(0))
}
``` 
Whilst this should work if the input is a correctly managed boolean (in which all the bits are zero except for the LSB which represents the boolean value), this function will behave incorrectly on less well-formed inputs. For example the negation of `0b11111110` should be true however the above code will return false. From the P-code reference:
> This is a logical negate operator, where we assume input0 and output are boolean values. It puts the logical complement of input0, treated as a single bit, into output. Both input0 and output are size 1. Boolean values are implemented with a full byte, but are still considered to only support a value of true or false.

**Comment by Enkelmann** [comment]
Yes, you are right. To solve this we could either trim the input byte to a single bit or we could just add an assertion to make sure that only 0 or 1 is contained in the input byte. The latter would be a possible solution, because in principle it would be our own fault anyway if we put anything else than 0 or 1 into a boolean value. I will probably experiment a little with the assertion solution before I decide which way to go for the fix.
