### ISSUE TITLE
ghidra plugin failed

### ISSUE THREAD

**Issue by Shmily8421** [fkie-cad/cwe_checker#298]
`Execution of Ghidra plugin failed: Process was terminated.`
`2022-03-16 12:04:53,639 main ERROR No logging configuration`
When I run cwe_checker, it failed.

**Comment by Enkelmann** [comment]
Can you share some more information on what happened? For example, what Ghidra version are you using? Does the error only happen for a particular input binary or for every binary? What version of the cwe_checker do you use? Since I have not yet encountered this error myself, I do not know the root cause of it.

**Comment by Shmily8421** [comment]
I get [ghidra_9.2_PUBLIC](https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_9.2_build/ghidra_9.2_PUBLIC_20201113.zip) from NSA's repositories on github.
And get cwe_checker_0.6.0 source from your repository
And I follow the README compile cwe_checker locally.
When test the case including double free and null pointer，it throw a error said the ghidra plugin failed.

**Comment by Shmily8421** [comment]
In fact, may u told me your runtime environment.
I want to run cwe_checker locally,

**Comment by Enkelmann** [comment]
Could you try to use the latest Ghidra version instead (10.1.2)? The old Ghidra versions contain a vulnerable version of the log4j logging library and therefore should not be used anymore anyway. Since your error message mentions logging, this may be related to that. If this should fix your issue then I will have to update the Readme accordingly. Now that I think about it, I should update the Readme in any case...
Another thing you could do is try out the Docker container instead of a locally installed version. Since the Docker container is tested in our CI this should work out of the box.

**Comment by Shmily8421** [comment]
OK, but I want to debug cwe_checekr, so I wan to run it locally.
By the way, what country are you from?

**Comment by Enkelmann** [comment]
Then try using the latest Ghidra version. Any further debugging only makes sense if we know that the Ghidra version is not the culprit for your problems.

The Fraunhofer FKIE is a German research institute. I am also German, which may explain any English grammar mistakes I make. ;-)

**Comment by Enkelmann** [comment]
I am not on any social networks. But you can reach the cwe_checker team via E-Mail under the address `firmware-security@fkie.fraunhofer.de` or me personally via `nils-edvin.enkelmann@fkie.fraunhofer.de`.

**Comment by Shmily8421** [comment]
This is my process of compile, code case, run cwe_checker and fail

**Comment by Enkelmann** [comment]
Since this issue has been resolved I am closing this. For the interested reader, it was apparently due to missing privileges for the Ghidra install folder.

**Comment by Kasey0727** [comment]
Excuse me, but I also encountered the same problem as mentioned above. I need to run **cwe_checker** locally, too, and I received the same error when executing the `cwe_checker BINARY` command: 
`Execution of Ghidra plugin failed. Use the --verbose flag to print Ghidra output for troubleshooting.`

My runtime environment is:
- **ghidra 11.2** [ghidra_11.2_PUBLIC_20240926.zip](https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_11.2_build/ghidra_11.2_PUBLIC_20240926.zip)
- **rust 1.83.0**
- **java 21.0.5 2024-10-15 LTS**
- the latest source code of **cwe_checker** from this very GitHub repository

And I have compiled **cwe_checker** locally according to the requirements in the README.

I look forward to your reply and would be very grateful ^_^
