### ISSUE TITLE
What's the meaning of subs?

### ISSUE THREAD

**Issue by Shmily8421** [fkie-cad/cwe_checker#303]
![image](https://user-images.githubusercontent.com/62237611/159600523-e17ecd54-fdc8-436b-85ea-b597cfd52bb0.png)
"subs" appears in many places. but I can;t know it's understand what it meant.

**Comment by Enkelmann** [comment]
`subs` is just shorthand for subfunctions. So every function inside the binary is a `Sub`. Functions of dynamically loaded libraries are also subfunctions, but because we do not know their content we save knowledge about them differently (namely as `ExternSymbol`). The `Tid` you see in the screenshot is just an unique identifier for a subfunction (which can be used for both internal function and extern symbols).
