### ISSUE TITLE
What's the meaning of block.term.jmps?

### ISSUE THREAD

**Issue by Shmily8421** [fkie-cad/cwe_checker#305]
The block has tid, which is a blk_id. And another attribute "term" has instr_id, what's meaning of it?
![image](https://user-images.githubusercontent.com/62237611/159833487-beed24ae-25e1-40d0-af5f-7af9dd33c52e.png)

**Comment by Enkelmann** [comment]
Your picture only shows the `Tid`, which consists of a unique ID and the address that this ID belongs to. Note that addresses themselves are not unique identifiers, because one assembly instruction can be translated to many instructions in the intermediate representation, all of which share the same address.
