### ISSUE TITLE
Waht is the logic to check CWE476(NULL Pointer Dereference)?

### ISSUE THREAD

**Issue by Shmily8421** [fkie-cad/cwe_checker#309]
I read the comment, but I can't understand the logic of the code.
Can you explain how dose the code check?
cwe476 is NULL pointer dereference.
![image-20220325210601208](https://shmily8421.oss-cn-beijing.aliyuncs.com//image/image-20220325210601208.png)

**Comment by Enkelmann** [comment]
This is a classical taint analysis. We taint the return values of functions that may return `Null` instead of a pointer (e.g. malloc). Then we follow the data flow of the tainted values until we either find a conditional jump where the condition checks a tainted value for being zero (which means no bug) or until the program tries to access memory through a tainted value (which may be a Null dereference, since the program did not check whether the tainted value is Null or not).

Your screenshot only shows the logic for setting up the taint source. The real data flow magic (that happens via a fixpoint computation on the control flow graph) all happens in the `computation.compute_with_max_steps(100);` call.

**Comment by Shmily8421** [comment]
Ok, I will learn the taint analysis.
By the way, have you ever published some paper on the cwe_checker?

**Comment by Enkelmann** [comment]
We are working on publishing papers about the cwe_checker, but have not yet. When we do, we will make sure to announce it in the Readme.

**Comment by Shmily8421** [comment]
So you're going to iterate over all the edges, set the target of the edges to a taint source, and then use fixpoint to trace the data flow?

**Comment by Shmily8421** [comment]
I don't quite understand the correlation between taint analysis and fixpoint.

**Comment by Shmily8421** [comment]
After a period of research, my current understanding of CC is.
It calls ghidra to generate an assembly file, then constructs the ICFG and gives it to the checker for pattern matching.
For several that use function symbol matching, such as cwe676 (Use of Potentially Dangerous Function), it is easy to understand.
But cwe476 is hard to understand, is it doing fixed-point analysis on ICFG? Can you elaborate on that?
Much appreciated.

**Comment by Enkelmann** [comment]
CWE-476 fixpoint algorithm on the ICFG in a nutshell:
- Step 1: The taint sources are return registers of functions like `malloc` that can return null pointers. Taint them at the corresponding CFG nodes.
- Step 2: For every edge in the CFG, taint all registers and positions in memory at the target node whose values may depend on a tainted value from the source node. With two exceptions:
  - If the edge checks a tainted value for being zero, do not taint anything at the target node.
  - If the operation represented by the edge may dereference a tainted value, then generate a CWE warning. Do not taint anything at the target node if a CWE warning is generated.
- Now iterate step 2 until a fixpoint is reached (i.e. no more taint is generated by further iterations)
- Step 3: Return the CWE warnings generated during step 2.

I simplified the stuff that actually happens in the algorithm a bit for easier understanding. I hope that this gives you a better starting point for understanding the actual algorithm.

**Comment by Enkelmann** [comment]
On a very high level, taint analysis is just tracking the data flow on the CFG from taint sources to sinks. And the fixpoint algorithm is just a way of computing the data flow over the CFG.

**Comment by Shmily8421** [comment]
OK, how do you make the abstraction and the transfer functions?

**Comment by Shmily8421** [comment]
And have u done an alias analysis?

**Comment by Enkelmann** [comment]
> OK, how do you make the abstraction and the transfer functions?

You can look that up in the code of the CWE-476 check. The abstract state assigned to each node is defined in by the `State` struct, while the transfer functions are defined in the `Context` trait implementation of the `Context` struct.

> And have u done an alias analysis?

Not in this check. For the type of null pointer dereferences that this check looks for this is usually not necessary, since a correct null check usually follows directly after the call to the null pointer creating function (`malloc`, etc.).

**Comment by Shmily8421** [comment]
If I want to use mathematical symbols to represent abstract and transfer functions, how can I do?
Like I use `+` stand for a positive number, `-` stand for a negative number, `o` stand for zero, `top` stand for unknown, `bot` stand for undefined.
And the transfer is `+` + `+` = `+`, `+` - `+` = `top`, etc

**Comment by Enkelmann** [comment]
Generally, `tainted + untainted => tainted`. Regardless of the binary operation. But for details, corner cases, and so on you really have to look into the code.

**Comment by Shmily8421** [comment]
> Generally, `tainted + untainted => tainted`. Regardless of the binary operation. But for details, corner cases, and so on you really have to look into the code.

Thank you for your answer, I just started static analysis, so many concepts are not very clear, please forgive me.

**Comment by Shmily8421** [comment]
> Generally, `tainted + untainted => tainted`. Regardless of the binary operation. But for details, corner cases, and so on you really have to look into the code.

Do I need to look at the code in the abstraction_domain folder?

**Comment by Enkelmann** [comment]
To understand the CWE-476 check it should suffice to look at the code in the `src/cwe_checker_lib/src/checkers/cwe_476` folder plus the `src/cwe_checker_lib/src/checkers/cwe_476.rs` module file. If you use something like Visual Studio Code you can then simply follow the references in the code to other relevant code parts whenever necessary.

**Comment by Shmily8421** [comment]
> To understand the CWE-476 check it should suffice to look at the code in the `src/cwe_checker_lib/src/checkers/cwe_476` folder plus the `src/cwe_checker_lib/src/checkers/cwe_476.rs` module file. If you use something like Visual Studio Code you can then simply follow the references in the code to other relevant code parts whenever necessary.

Okay. And have you consulted any information? Or is there any information to facilitate understanding? Reading code to understand logic is a very difficult task.

**Comment by Enkelmann** [comment]
I know, but I hope that the documentation comments in there will help you. It is also helpful to read up on static taint analysis in the context of binary analysis in general beforehand, but I do not have a good reference for that. I learned it mostly by reading research papers, but these are also hard to read if you are new to the topic.

**Comment by Shmily8421** [comment]
> I know, but I hope that the documentation comments in there will help you. It is also helpful to read up on static taint analysis in the context of binary analysis in general beforehand, but I do not have a good reference for that. I learned it mostly by reading research papers, but these are also hard to read if you are new to the topic.

Okay, nachdem ich es eine Weile gesehen hatte, stellte ich fest, dass das Verständnis der Details immer klarer wurde.

**Comment by Shmily8421** [comment]
The algorithm is actually solving the path problem from generating the pointer to the reference pointer, but only through taint analysis.

**Comment by Shmily8421** [comment]
I have now analyzed the order of taint, state, and context, and basically understand the operation logic. But I don't understand pointer_inference_state properties in the context. I don't know what it does, but it keeps appearing in the functions.
Like that.
![1653569597(1)](https://user-images.githubusercontent.com/62237611/170491464-8ed43556-1ad1-464e-b7d0-b5f9410d9c2c.jpg)

**Comment by Shmily8421** [comment]
And why the `Computation::node_priority_list` need to be sorted in weak topological order?

**Comment by Enkelmann** [comment]
The Pointer Inference is a combined points-to and value-set analysis, i.e. it computes the targets of known pointers and also known absolute values of registers and memory. The CWE-476 check uses it to query the values of registers and memory so that it can trace when a potential Null pointer was written to the stack and then loaded from the stack again before being either dereferenced or checked for being Null.

When the CWE-476 check was written the Pointer Inference did not have a nice interface for querying values. Thus the check does some ugly housekeeping to keep track of the local Pointer Inference state itself so that it can correctly query its results. Since then the Pointer Inference got a better interface, but the CWE-476 check was not yet refactored to use the new interface.

**Comment by Enkelmann** [comment]
The sorting of the `Computation::node_priority_list` has the goal of speeding up the computation by ordering the nodes of the control flow graph in a specific way. The algorithm then tries to compute the fixpoint at nodes at the beginning of the list before it tries to compute the fixpoint for nodes at the end of the list. For this check you can totally ignore it, since the algorithm should converge to a fixpoint pretty fast even if you order the nodes in a totally random order.
