### ISSUE TITLE
Ghidra could not be executed:Permission denied

### ISSUE THREAD

**Issue by Gloriapp** [fkie-cad/cwe_checker#314]
I installed the cwe_checker in my docker container, but the following error occurred when executing the **cwe_checker binary**:
```
Error: Ghidra could not be executed:
Permission denied (os error 13)
```
Is it because of user permissions for my Docker container mount directory or something else?

**Comment by Enkelmann** [comment]
Most likely this is due to the user executing the cwe_checker binary not having the necessary permissions to execute the `analyzeHeadless` binary in the Ghidra folder. If you want to build your own Docker image I recommend starting with the Dockerfile contained in this repository, since there we made sure to not run into problems like that.

**Comment by Enkelmann** [comment]
Since there was no further response from the issue creator I am assuming this to be resolved. Closing the issue.
