### ISSUE TITLE
How to output the struct `project` and `control_flow_graph` as json format?

### ISSUE THREAD

**Issue by Shmily8421** [fkie-cad/cwe_checker#316]
I use that code, but the the program running, throwing a error "serde_json::tostring key must be a string"
![image](https://user-images.githubusercontent.com/62237611/163657388-d9f7a87c-787c-4e03-aeff-e9f6df0e907c.png)

**Comment by Enkelmann** [comment]
Sorry for the late answer, I was on holiday. Right now you cannot convert the `Project` struct to JSON this way. The reason for this is that the struct contains some maps from keys to structs where the keys are `TID`s and not strings, but JSON can only represent maps where the keys are strings. One possible solution for serializing the project struct anyway is to use another output format. If I remember correctly, YAML instead of JSON should just work.
The serialization of the control flow graph probably suffers from the same problem, although I am unsure what data structure exactly is causing it to fail there.

**Comment by Shmily8421** [comment]
It is work!

**Comment by Shmily8421** [comment]
And the `IR::Project` can be written by json format.

**Comment by Enkelmann** [comment]
I assume that means that I can close the issue. :) Feel free to reopen if I am wrong.
