### ISSUE TITLE
Add support to AArch64 machine

### ISSUE THREAD

**Issue by cascades-sjtu** [fkie-cad/cwe_checker#320]
As I'm using M1 Pro MacBook, it's very slow to run the original cwe_checker(amd64) docker (maybe it's because docker using qemu-system to support different architecture without hardware acceleration). So I want to create another version of Dockerfile that will build AArch64 image, and that image will run significantly faster than the original one.

**Comment by Enkelmann** [comment]
Thank you for your PR! Especially since another user recently reported some problems when running the Docker images on Mac in issue #313.

To keep all the corresponding discussions in one place I suggest using the pull request #321 from now on for all future discussions on this. But I will keep the issue thread open until the pull request is merged.

**Comment by cascades-sjtu** [comment]
OK, I'll follow your suggestion.👌

**Comment by Enkelmann** [comment]
For those who did not follow the discussion in #321: Thanks to the help provided by @cascades-sjtu we do now deploy multi-architecture builds of the cwe_checker Docker image to Dockerhub (see PR #322), resolving this issue. :-)
