### ISSUE TITLE
Execution of ghidra plugin failed

### ISSUE THREAD

**Issue by anzosasuke** [fkie-cad/cwe_checker#345]
I was trying to analyze a binary when i got this. It works for other binaries i have though. Erroe looks like this. how do I fix this?

[sgcc.zip](https://github.com/fkie-cad/cwe_checker/files/9144820/sgcc.zip)

`Execution of Ghidra plugin failed: Process was terminated.
 
ERROR Abort due to Headless analyzer error: Java heap space (HeadlessAnalyzer) java.lang.OutOfMemoryError: Java heap space`

**Comment by Enkelmann** [comment]
The cwe_checker is not optimized for analyzing large binaries. While we would like to enable that, this would require some serious engineering effort for which we currently lack the manpower. Instead our main focus right now is on improving analysis quality for binaries compiled from C-code, which tend to be much smaller than your binary.

In your case the binary is over 10 MB large (even after stripping it). When serializing its content for the cwe_checker (a process which is currently not optimized for size) we either hit some Ghidra-internal heap size limit or your whole system ran out of RAM space in the process. So using a machine with more RAM may or may not solve this issue for you. But I do not recommend analysis of such large binaries with the cwe_checker at the moment anyway, since they usually are not compiled from C-code.

Closing the issue, since we sadly won't do anything about this type of problem until we can get some more people working on the project. Sorry.
