### ISSUE TITLE
ghidra >= 10.2 fix "getLeastSignificatBitInBaseRegister" spelling wrong

### ISSUE THREAD

**Issue by Vang3lis** [fkie-cad/cwe_checker#367]
https://github.com/NationalSecurityAgency/ghidra/issues/4255

**Comment by Enkelmann** [comment]
Sorry for the late answer, I was on holiday break.

Yes, we have to fix this. Since the fix will enforce the usage of the newest Ghidra version (including the need for a newer Java version than what is needed currently), it may take a little longer than usual before I can push this to the master branch. Until then one needs to use an older Ghidra version, e.g. Ghidra 10.1.5, for the cwe_checker.

**Comment by Enkelmann** [comment]
Thanks to PR #368 this is now fixed on the master branch. Note that as a result, Ghidra >= 10.2 is now required for the cwe_checker, while older versions (like the current stable version) still require Ghidra <= 10.1.5.

Also as an important note: If you have a previous version of the cwe_checker installed, you need to execute `make uninstall` before installing the newer cwe_checker version.
