### ISSUE TITLE
Some comments seems confusing

### ISSUE THREAD

**Issue by Brubbish** [fkie-cad/cwe_checker#390]
What do these comments mean:

"The `sub` a block is associated with is the `sub` that the block is contained in in the `program` struct. "Which is in file \src\cwe_checker_lib\src\analysis\graph.rs
"Using dataflow analysis, we search for an execution path where a memory access using the return value of a symbol happens before the return value is checked through a conditional jump instruction." Which is in \src\cwe_checker_lib\src\checkers\cwe_476.rs

Also, I found some other comments that need to think carefully to understand, so if you don't mind, I would like to make some PRs about that.
But I'm not a native speaker in EN too :D

**Comment by Enkelmann** [comment]
Comment meanings:
- "The `sub` a block is associated with is the `sub` that the block is contained in in the `program` struct. " --> Oops, this comment is not valid anymore. There was a time where one block could be contained in more than one function in the `program` struct and the control flow graph generation had to somehow handle this situation, because this is not allowed in the generated control flow graph. But nowadays we have a normalization pass that ensures that each block is only contained in one `sub` in the `program` struct. So we should remove this comment, as it is obviously only confusing for readers...
- "Using dataflow analysis, we search for an execution path where a memory access using the return value of a symbol happens before the return value is checked through a conditional jump instruction." --> What happens: We follow return values of functions like `malloc`, that may return NULL pointers, through the control flow graph. When the return value is checked for being NULL (in a conditional jump instruction), we stop following it. When the return value is used in any kind of memory access, we generate a CWE warning for it (and then also stop following it). The general technique used for following values through the control flow graph is *dataflow analysis*. Does this clear things up? Feel free to propose a better formulation for this confusing sentence. :-)

I am very happy about every PR improving the documentation quality, so feel free to open as many PRs as you like! :-) And do not worry about your English, it seems fine to me and I can help you fix any mistakes (although I am also not a native EN speaker). :-)

**Comment by Brubbish** [comment]
Oh I see, when we find a conditional judge toward the pointer like "a=malloc(10); if (a) ...; else ...", we check if the pointer 'a' is used in the following 'else' codes, and if it is true, we then can make a warning about which. 
So, we judge this CWE when the return value is not being checked and when it is 100% NULL, right?

**Comment by Enkelmann** [comment]
The implementation actually only judges this to be a CWE when it is not being checked, but not when it is 100% NULL. The reason for this was because it reduces the number of false-positive warnings and it was easier to implement. In theory the 100% NULL case can nowadays be catched by another check, namely the `Memory` check, although it still produces a lot of false positives.

**Comment by Brubbish** [comment]
Thanks, I think I've got the idea and the previous confusing formulation seems quite clear now LOL.
I think we can close this one.
