### ISSUE TITLE
What is CWE119 specifically and the difference with its variants

### ISSUE THREAD

**Issue by Brubbish** [fkie-cad/cwe_checker#395]
I tested cwe_119 in `/test/artificial_samples` and the results are like:
> [CWE125] (0.3) (Out-of-bounds Read) Memory read at 0010123c may be out of bounds
[CWE125] (0.3) (Out-of-bounds Read) Memory read at 001012ff may be out of bounds
[CWE787] (0.3) (Out-of-bounds Write) Memory write at 001011f8 may be out of bounds.
[CWE787] (0.3) (Out-of-bounds Write) Memory write at 001012a9 may be out of bounds.
[CWE476] (0.3) (NULL Pointer Dereference) There is no check if the return value is NULL at 0010127d (calloc).
[CWE476] (0.3) (NULL Pointer Dereference) There is no check if the return value is NULL at 001012d2 (malloc).

and when I test two samples I have in PWN challenge, which should be a vulnerability concerned with off-by-one(CWE-193) and the other is about stack overflow, the result shows like below respectively, and the places that trigger the bugs are not quite correct:
> off-by-one-b00ks:
[CWE119] (0.3) (Buffer Overflow) Call to free at 0010119d may access out-of-bounds memory.
[CWE119] (0.3) (Buffer Overflow) Call to free at 001011b0 may access out-of-bounds memory.

> stackoverflow-brop 
[CWE119] (0.3) (Buffer Overflow) Call to read at 00400744 may access out-of-bounds memory.

**Comment by Brubbish** [comment]
Is CWE119 only judged by symbol names and its buffer size represented in function `handle_call` in `cwe_checker_lib/src/checkers/cwe_119/stubs.rs` ?

**Comment by Enkelmann** [comment]
The warnings in your PWN challenge are most likely false positives, i.e. the cwe_checker currently cannot identify the actual overflows in those binaries. You can get some more information on why the cwe_checker reported a CWE warning at a specific program point by looking at the alternative JSON output (via the `--json` command line flag). False positives at calls to `free` are usually due to the cwe_checker thinking that the buffer size might be zero. I am currently thinking about how to handle this case better, which is somewhat complicated by the fact that the behavior of `malloc(0)` is implementation-specific.

The most important restriction to the CWE-119 analysis at the moment is that it can only find overflows for memory objects where it can identify the size of the object as a concrete number known at compile time (e.g. something like `buffer = malloc(200);`). But if a buffer size is only known at execution time (e.g. a buffer that is as large as some input file) then we do not generate any CWE warnings as we would produce way too many false positives with the current implementation. But this is a solvable problem that is just not yet implemented. It is also very high on my priority list, so I hope that I can implement such detection capabilities in the upcoming months.

**Comment by Brubbish** [comment]
What about the result in testing `/test/artificial_samples/cwe_119.c` that only printed warnings for CWE125 and CWE787? I am still a little bit confused about the differences between CWE_119 and CWE_125&787.

**Comment by Enkelmann** [comment]
- CWE-125: Buffer overflow through an operation that reads from memory. This often leads to information exposure bugs.
- CWE-787: Buffer overflow through an operation that writes to memory. Such bugs can often be exploited to reach arbitrary code execution.
- CWE-119: A general buffer overflow. We use this mainly for function calls where we do not know whether the called function reads from or writes to the memory object in question. I.e. CWE-125 and CWE-787 are special cases of CWE-119 and we only annotate CWE-119 if we cannot decide whether CWE-125 or CWE-787 would be more appropriate.

**Comment by Brubbish** [comment]
So, it is like, CWE-125&787 are for out-of-bounds read&write in both heap and stack, and all other cases suspected to have buffer overflow belongs to CWE-119 right?
Is there anything I can do for improving the quality of this check

**Comment by Enkelmann** [comment]
> So, it is like, CWE-125&787 are for out-of-bounds read&write in both heap and stack, and all other cases suspected to have buffer overflow belongs to CWE-119 right?

Yes.

Regarding check improvement: Well, the next step is to track relations between values and to track which values correspond to the size of memory objects. But to implement corresponding analysis improvements is quite involved. That might be difficult if you are still new to this type of analysis approach.

**Comment by Brubbish** [comment]
Thanks a lot.
I may start with the sample that triggers false positives (e.g. free()), find out what has happened there, and see what I can do next.
