### ISSUE TITLE
Project Normalization consumes too much RAM

### ISSUE THREAD

**Issue by ravenolf** [fkie-cad/cwe_checker#410]
Hello! 

I want to report an issue that I believe to be an infinite loop of some sort that I faced when running CWE Checker Lib on a binary. This issue is causing the project normalization to consume large amounts of RAM. 

**Input:**
The binary was an old version of lrzip (I can provide it along with compilation details privately). The compiled binary was relatively small (size was 575K), yet the analysis ran for over 30 minutes, consuming over 40Gb of RAM, and ended up getting killed due to OOM-kill.

**Analysis**:
I use cwe_checker_lib (commit `d84f517`) as part of a bigger rust program. In it, I use [disassemble_binary](https://github.com/fkie-cad/cwe_checker/blob/1fcc30cbaede5f7b3a83fd28ce744ac3d1d26706/src/cwe_checker_lib/src/pipeline/mod.rs#L17). When I tried debugging the issue, I found the memory consumption happening around the `project.normalize()` call. More specifically I believe it is related to the fixpoint analysis.
To confirm the issue happens even outside of my program I tried running the program on cwe_checker and the memory issue remained (albeit I tested it on a smaller machine).

**Summary**:
I understand cwe_checker can sometimes consume large amounts of RAM but this binary is fairly small I believe this could be a bug If you can help me understand the issue and deal with it I would be very grateful.

**Comment by Enkelmann** [comment]
Yes, what you encountered is definitely a bug in the cwe_checker. And for bugs leading to consumption of large amounts of RAM it is safe to assume that some fixpoint computation is the culprit. But the project normalization already contains more than one fixpoint computation, so I still need to do some pinpointing to get to the source of the issue.

If you can provide the binary in question I will be happy to take a look at it! As for private channels, you can reach us at firmware-security@fkie.fraunhofer.de (our research group) or me directly via the E-mail address hidden in the Cargo.toml files. I also hang out in the [gitter channel of the FACT project](https://app.gitter.im/#/room/#FACT_core_community:gitter.im) if you prefer gitter over E-mail.

I am also happy to learn of people experimenting with using the cwe_checker_lib directly. It is a goal of the project to also provide a framework for writing new binary analysis tools for everyone, but due to a lack of manpower we are still far away from reaching that goal. E.g. there are currently no tutorials explaining the inner workings of the cwe_checker apart from the source code documentation.

**Comment by Enkelmann** [comment]
Thank you for providing a test case! I was able to identify and solve the issue. The fix is contained in PR #412, which should be merged later today. If you need to work with a specific commit version of the cwe_checker, you can also backport the fix in #412 to that version, the necessary code changes are quite small.
