### ISSUE TITLE
Compiled Juliet 1.3 C/C++ Test Suite Issues

### ISSUE THREAD

**Issue by DwarDoh** [fkie-cad/cwe_checker#54]
I have compiled the [Juliet 1.3 C/C++ test suite](https://samate.nist.gov/SRD/testsuite.php) as both a Windows executable and Ubuntu 16.04 ELF and ran BAP w/cwe_checker against both. I am using the fkiecad/cwe_checker container image from docker hub. 

Neither executable assessment completes correctly. The Win10 EXE assessment produces the error: 'Fatal error: out of memory.' after ~1 minute, and the ELF assessment never returns, with no output from either standard out or err. I have attached archives of the two executables to this issue ticket. 

Win10 EXE: [Testcases.zip](https://github.com/fkie-cad/cwe_checker/files/4371840/Testcases.zip)
Ubuntu 16.04 ELF: [Juliet1.zip](https://github.com/fkie-cad/cwe_checker/files/4371842/Juliet1.zip)

I have had success with assessment of smaller executables using the same configuration and methodology.

**Comment by Enkelmann** [comment]
Did you use the latest or the stable tag of the docker image? Although it probably doesn't matter, as main problem is in fact the binary size.

BAP uses a lot of memory and needs a lot of time to disassemble large binaries. Personally, I did not try to disassemble binaries larger than 20 MB with it yet as BAP usually fails to disassemble binaries of that size. The Juliet binary is about 50 MB (stripped).

If you have used the stable tag (which is based on the old BAP 1.6), you can try the latest tag of the cwe_checker docker image (which uses a snapshot of the BAP master branch). BAP 2.0 made progress on the disassembly of large binaries, but I have not yet tested how much progress.

The support of Windows PE files is still very experimental. I am eager to hear some user reports, but I don't expect the cwe_checker to run flawlessly for them yet. The reported out of memory error occurs during the BAP disassembly process (before the cwe_checker is run), so there is nothing I can do on the cwe_checker side.

**Comment by DwarDoh** [comment]
I was using the stable tagged version. I switched to the latest and re-ran the tests. Thanks for the suggestion.

Now the win10 exe analysis does not error out, and runs to completion in ~1 hour. However, no issues are detected at all (the test suite injects 100s of CWE issues in the source). The Ubuntu build still runs without finishing (I stopped it after 7 hours), with no issues displayed during that time.

**Comment by Enkelmann** [comment]
Is it possible to only compile a part of the test suite to a smaller binary? If no issues at all are displayed, it still sounds to me like BAP fails to properly disassemble the binary due to its size.

The Juliet Test Suite is aimed at evaluating source code analysis tools. Some of the injected CWEs will not be present after compilation (mainly due to compiler optimizations). But no CWEs in the binary is certainly a bug on our side.

If the Ubuntu build does not terminate, it will not display CWEs, as they are only printed out at the end. The question is only whether BAP or the cwe_checker does not terminate here. You could try `bap BINARY -d` to find out whether BAP can disassemble the file in finite time.

**Comment by XVilka** [comment]
@DwarDoh there were some significant improvements in BAP since the issue was opened. Could you please retry with the current master and report the issue in https://github.com/BinaryAnalysisPlatform/bap/issues if still present?

**Comment by DwarDoh** [comment]
Hello Anton, thanks for the update.

I am using the cwe_checker docker container for my work, not BAP directly.
If its latest image has the latest BAP you speak of, I would be happy to
test.

Let me know. Thanks.

**Comment by ivg** [comment]
@DwarDoh, we in BAP use the Juliet set extensively with pretty impressive results. However, we do not compile the whole suite into one binary but instead create a binary per each CWE/case. Concerning the size, BAP can disassemble 50Mb binaries, but it will take 50Gb of memory and about an hour of work. Not surprising, given the amount of work that BAP does underneath the hood, e.g., it builds a full control flow graph for each subroutine.

**Comment by Enkelmann** [comment]
I am closing this issue for now. Compiling the test cases for each CWE in the test suite separately produces binaries that are small enough for the cwe_checker, so this is a viable workaround. And since most of the work is still done on the BAP side, we cannot do much about the resource consumption when disassembling large binaries on the cwe_checker side.
