### ISSUE TITLE
Error while executing

### ISSUE THREAD

**Issue by 0xd3xt3r** [fkie-cad/cwe_checker#55]
File : ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-, for GNU/Linux 3.7.0, stripped

`no signatures for specified compiler and architecture
Failed to create a project: no entry
Backtrace:
Raised at file "src/error.ml" (inlined), line 9, characters 14-30
Called from file "src/or_error.ml", line 74, characters 17-32
Called from file "lib/bap/bap_project.ml" (inlined), line 192, characters 15-29
Called from file "lib/bap/bap_project.ml" (inlined), line 193, characters 35-41
Called from file "lib/bap/bap_project.ml", line 272, characters 19-36
Called from file "src/or_error.ml", line 66, characters 9-15
`

**Comment by 0xd3xt3r** [comment]
Does cwe_checker support 64-bit ARM ?

**Comment by Enkelmann** [comment]
Unfortunately, BAP does not support 64-bit ARM at the moment. They are planning to, but I don't know whether they already have a timetable for it. You can ask them in the [BAP gitter channel](https://gitter.im/BinaryAnalysisPlatform/bap) if you want to know more.

Closing the issue for now, since we need to wait for BAP to support new architectures.

**Comment by firmianay** [comment]
Does cwe_checker support 64-bit ARM using ghidra now?

**Comment by Enkelmann** [comment]
Yes, 64-bit ARM is now supported by both Ghidra and the cwe_checker.

**Comment by firmianay** [comment]
I tried to analyze the Android so, one of ten files scanned successfully, so sad...

**Comment by Enkelmann** [comment]
Feel free to open issues for those that do not work. Keep in mind that we currently focus on supporting Linux ELF files. So for example Android DEX files are currently not supported by the cwe_checker.

**Comment by firmianay** [comment]
Seems to be a problem with ghidra not cwe_checker:
```
Bluetooth/lib/arm64/libbluetooth_jni.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[md5/uuid]=0e6b29cbb6cb0f395e9babec5ba91c27, stripped
```
```
Execution of Ghidra plugin failed: Process was terminated.
INFO  REPORT: Save succeeded for file: /elf (HeadlessAnalyzer)  
INFO  REPORT: Post-analysis succeeded for file: /elf (HeadlessAnalyzer)  
```

**Comment by Enkelmann** [comment]
If the file is rather large, this may be due to running out of RAM. We are unable to handle larger binaries (I would guess about 10MB and more) at the moment anyway, because the analysis times explode for larger binaries (but we are working on improving this). If the binary is not that large, it could still be a bug in the Ghidra script used by the cwe_checker. If you are able to open the file directly in Ghidra without issue, then it is a cwe_checker bug.
