### ISSUE TITLE
-out option not working when running emulation checks

### ISSUE THREAD

**Issue by curtlawson** [fkie-cad/cwe_checker#63]
While attempting to run cwe-checker for CWE415 against one of the individually built Juliet Test Suite for C/C++ Version 1.3 test cases, I am unable to get the output directed to a file using the -out option.

I am running the following versions:
- cwe-checker 0.3-dev
- bap 2.1.0-alpha+5937def

See attached screenshot for behavior.

![cwe_checker](https://user-images.githubusercontent.com/8866668/83659749-8fce8380-a589-11ea-904e-f69d879027c1.PNG)

**Comment by Enkelmann** [comment]
It should work if you replace
```
cwe-checker-out=foo.json
```
with
```
cwe-checker-emulation-out=foo.json
```
since the name of the emulation plugin is `cwe-checker-emulation`. So if you want to generate json-output for the emulation plugin, you also have to type `cwe-checker-emulation-json` instead of `cwe-checker-json`. The `-partial` option currently does not work with the emulation based checks.

As of right now, the command line options for the emulation based checks are not properly documented anywhere. I will leave this issue open until we fix this.

**Comment by Enkelmann** [comment]
We decided to deprecate the emulation-based checks, so I am closing this issue. You can find better-maintained versions of these checks in the [BAP toolkit](https://github.com/BinaryAnalysisPlatform/bap-toolkit).
